// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var fs, gcloud, keyFilename, projectId;

  gcloud = require('gcloud');

  fs = require('fs');

  projectId = process.env.GCLOUD_TESTS_PROJECT_ID;

  keyFilename = __dirname + "/../key.json";

  exports.location = exports.lastLocation = function() {
    return projectId + ":" + keyFilename;
  };

  exports.cleanup = function(callback) {
    var ds, q;
    ds = gcloud.datastore.dataset({
      projectId: projectId,
      keyFilename: keyFilename
    });
    q = ds.createQuery('Level');
    return ds.runQuery(q, function(error, results) {
      var keys;
      if (error != null) {
        return callback(error);
      }
      keys = results.map(function(d) {
        return d.key;
      });
      return ds["delete"](keys, callback);
    });
  };

  exports.setUp = function(t) {
    return exports.cleanup(function(error) {
      t.error(error, 'cleanup returned an error');
      return t.end();
    });
  };

  exports.tearDown = function(t) {
    return exports.setUp(t);
  };

  exports.collectEntries = function(iterator, callback) {
    var data, next;
    data = [];
    next = function() {
      return iterator.next(function(error, key, value) {
        if (error != null) {
          return callback(error);
        }
        if (!arguments.length) {
          return iterator.end(function(error) {
            return callback(error, data);
          });
        }
        data.push({
          key: key,
          value: value
        });
        return setTimeout(next, 0);
      });
    };
    return next();
  };

}).call(this);
